theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
exclude: [api, build.py, assets]
defaults:
  - 
    scope:
      path: "README.md"
    values:
      permalink: "index.html"
